url: "http://www.enteratlas.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
title: Atlas
description: "An original science fiction episodic VR saga set in a world beyond imagination. A project by The Soap Collective, a next-generation creative agency."

# Build settings
markdown: kramdown
permalink: pretty
